import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[cursor]
thickness = 0.15
unfocused_hollow = true

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[shell]
program = "/bin/zsh"
