format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$memory_usage\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$shell\
$character"""

[line_break]
disabled = true
