
[cursor]
thickness = 0.2
unfocused_hollow = true

[font]
size = 15

[font.normal]
family = "JetBrainsMono"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-frappe.toml"]

[terminal.shell]
program = "/usr/bin/fish"
