#!/bin/bash

xset s 300 5
xset r rate 400 100

setxkbmap -option caps:swapescape
setxkbmap -model pc105 -layout us,ua -variant qwerty -option grp:win_space_toggle

function start_bar() {
    killall -q polybar
    while pgrep -x polybar >/dev/null; do sleep 1; done
    polybar bar &
}

function configure_monitors() {
    monitors=$(xrandr --query | rg -w connected | wc -l)
    if [[ $monitors > 1 ]]; then
        xrandr --output DVI-D-1 --primary --left-of HDMI-0
        bspc monitor DVI-D-1 -d 1 2 3 4 5 6 7 8 9
        bspc monitor HDMI-0 -d 10
    else
        bspc monitor DVI-D-1 -d 1 2 3 4 5 6 7 8 9 10
    fi
}

bspc config border_width         2
bspc config window_gap           25
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config top_padding size
bspc config split_ratio          0.50
bspc config borderless_monocle   true

bspc rule -a Gimp state=floating follow=on state=tiled
bspc rule -a Zathura state=tiled

bspc config focused_border_color "#51afef"
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#51afef"
bspc config presel_feedback_color "#900000"

flameshot &
dunst &
nm-applet
nitrogen --restore
pgrep -x sxhkd > /dev/null || sxhkd &
xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock & disown

configure_monitors
start_bar
