syntax on
set exrc
set tabstop=8
set shiftwidth=4
set expandtab
set smartindent
set hlsearch
set noerrorbells
set noswapfile
set nobackup
set scrolloff=12
set showcmd
set hidden
set mouse=a
set encoding=utf-8
set cursorline
set nowrap
set linebreak
set ruler
set incsearch
set laststatus=2
set relativenumber
set number
set cursorline
set background=dark
set shortmess+=c
set clipboard+=unnamedplus
set list
set completeopt=menuone,noinsert,noselect
set updatetime=300
set t_Co=256
set termguicolors
filetype plugin indent on
