call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'JuliaEditorSupport/julia-vim'
Plug 'rust-lang/rust.vim'
Plug 'Yggdroot/indentLine'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'joshdick/onedark.vim'
Plug 'ayu-theme/ayu-vim'
" Plug 'gosukiwi/vim-atom-dark'
" Plug 'joshdick/onedark.vim'
" Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
" Plug 'lourenci/github-colors'
" Plug 'folke/tokyonight.nvim'
" Plug 'chriskempson/base16-vim/'
" Plug 'rakr/vim-one'
" Plug 'itchyny/landscape.vim'
" Plug 'AlessandroYorba/Sierra'
" Plug 'rakr/vim-two-firewatch'
" Plug 'NLKNguyen/papercolor-theme'
" Plug 'sainnhe/sonokai'
" Plug 'drewtempelmeyer/palenight.vim'
" Plug 'sainnhe/sonokai'
" Plug 'rakr/vim-two-firewatch'
" Plug 'sonph/onehalf', { 'rtp': 'vim' }
" Plug 'Lokaltog/vim-monotone'
" Plug 'christophermca/meta5'
" Plug 'AlessandroYorba/Alduin'
" Plug 'vivkin/flatland.vim'
" Plug 'benbusby/vim-earthbound-themes'
" Plug 'nanotech/jellybeans.vim'
" Plug 'kaicataldo/material.vim', { 'branch': 'main' }
" Plug 'kyazdani42/nvim-web-devicons'
" Plug 'aditya-azad/candle-grey'
" Plug 'drewtempelmeyer/palenight.vim'
" Plug 'lurst/austere.vim'
" Plug 'chriskempson/base16-vim'
" Plug 'jaredgorski/fogbell.vim'
" Plug 'glepnir/galaxyline.nvim' , {'branch': 'main'}
" Plug 'nvim-telescope/telescope.nvim'
" Plug 'neovim/nvim-lspconfig'
" Plug 'nvim-lua/completion-nvim'
" Plug 'romgrk/barbar.nvim'
" Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()
