#!/bin/sh

killall sxhkd dunst lemonbar.sh || sleep 1

xset r rate 400 100
xsetroot -cursor_name left_ptr
xrandr --output DVI-D-1 --primary --left-of HDMI-0
setxkbmap -model pc105 -layout us,ua -variant qweety \
    -option grp:win_space_toggle

bspc config border_width 1
bspc config window_gap 15

bspc config pointer_modifier mod4
bspc config pointer_action1 move

bspc config split_ratio 0.50

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#569CD6"
bspc config normal_border_color "#7e7e7e"
bspc config active_border_color "#ec7279"
bspc config presel_feedback_color "#569CD6"

monitors=$(xrandr --query | rg -w connected | wc -l)
if [[ $monitors > 1 ]]; then
    bspc monitor DVI-D-1 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6
else
    bspc monitor -d 1 2 3 4 5 6
fi

sxhkd &
dunst &
alacritty &
lemonbar.sh | lemonbar \
    -F "#abb2bf" \
    -B "#1e2127" \
    -g "x20+0+0" \
    -f "Iosevka Nerd Font:size=11:antialias=false:style=Bold" &

feh --bg-scale ~/pictures/wallpapers/night_ghibli.jpg
