#!/bin/sh

killall sxhkd dunst

# TODO: proper multi monitor handling
num_of_mon=$(xrandr --query | rg -w connected | wc -l)
if [[ $num_of_mon > 1 ]]; then
    bspc monitor DVI-D-1 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6

    xrandr --output DVI-D-1 --primary --left-of HDMI-0
else
    bspc monitor -d 1 2 3 4 5 6
fi

xset r rate 400 100
xsetroot -cursor_name left_ptr
setxkbmap -model pc105 -layout us,ua -variant qweety \
    -option grp:win_space_toggle

bspc config border_width 0
bspc config window_gap 10

bspc config pointer_modifier mod4
bspc config pointer_action1 move

bspc config split_ratio 0.50

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_border_color "#569CD6"
bspc config normal_border_color "#7e7e7e"
bspc config active_border_color "#ec7279"
bspc config presel_feedback_color "#569CD6"

sxhkd &
dunst &
alacritty &

feh --bg-scale ~/pictures/wallpapers/night_ghibli.jpg
