set -o vi
shopt -s histverify

test -r ~/.dotfiles/bash/env.bash && source ~/.dotfiles/bash/env.bash
test -r ~/.dotfiles/bash/aliases.bash && source ~/.dotfiles/bash/aliases.bash
test -r ~/.dotfiles/bash/func.bash && source ~/.dotfiles/bash/func.bash

test -f ~/.fzf.bash && source ~/.fzf.bash
test -r ~/.cargo/env && source ~/.cargo/env

eval "$(starship init bash)"
eval "$(zoxide init bash)"
